In [1]:
import numpy as np

In [3]:
mymat = np.ones((4,5))

In [4]:
mymat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
mymat[::2,::2]

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
from numpy.random import randint

In [11]:
randint(10,20)

12

In [12]:

mymat[::2,::2]=randint(10,20)

In [13]:
mymat

array([[15.,  1., 15.,  1., 15.],
       [ 1.,  1.,  1.,  1.,  1.],
       [15.,  1., 15.,  1., 15.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
mymat.shape

(4, 5)

In [19]:
for _ in range(5):
  randomidx_x = randint(0,mymat.shape[0])
  randomidx_y = randint(0,mymat.shape[1])
  mymat[randomidx_x,randomidx_y]=randint(20,30)


In [20]:
mymat

array([[15.,  1., 11., 23., 10.],
       [22., 26., 27.,  1.,  1.],
       [ 6., 22., 14.,  1., 26.],
       [ 1.,  1.,  1., 10.,  1.]])

In [22]:
mymat.argmax(axis=1)

array([3, 2, 4, 3])

In [23]:
mymat.argmax(axis=0)

array([1, 1, 1, 0, 2])

In [25]:
mymat.argmax()//mymat.shape[1]

1

In [26]:
mymat.argmax()%mymat.shape[1]

2

In [27]:
mymat[3,3]=0

In [28]:
mymat.argmin()

18

In [29]:
mymat.argmin()//mymat.shape[1]

3

In [30]:
mymat.argmin()%mymat.shape[1]

3

In [31]:
mymat[3,3]=1.

In [33]:
mymat

array([[15.,  1., 11., 23., 10.],
       [22., 26., 27.,  1.,  1.],
       [ 6., 22., 14.,  1., 26.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [35]:
mymat.argmin(keepdims=True)

array([[7]])

In [36]:
np.unravel_index(np.argmin(mymat, axis=None), mymat.shape)

(0, 1)

In [39]:
mymat[mymat==mymat.min()]

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
mymat == mymat.min()

array([[False,  True, False, False, False],
       [False, False, False,  True,  True],
       [False, False, False,  True, False],
       [ True,  True,  True,  True,  True]])

In [40]:
np.where(mymat == mymat.min())

(array([0, 1, 1, 2, 3, 3, 3, 3, 3]), array([1, 3, 4, 3, 0, 1, 2, 3, 4]))